### ISSUE TITLE
% of time left isn't possible

### ISSUE THREAD

**Issue by soguy** [BrianValente/yearprogress_mac#1]
Just bought the app. Thought it will help me with procrastination, however, if you don't allow presenting % of time left (like a battery percentage), it does the opposite job. Currently, the tool presents % of the time passed only. I don't think it will be tough to add this to the tool :)

**Comment by BrianValente** [comment]
Hello soguy!

You want it to work backwards, right? I mean from 100% to 0%.

I'll see if I can make it work today. Expect an update in the App Store in
a few days, Apple takes some time to accept it.

**Comment by soguy** [comment]
Thanks!!!

**Comment by BrianValente** [comment]
Done! Here's the new version:
https://github.com/BrianValente/timeprogress_mac/releases/tag/0.7

For the App Store release wait a few days.
