### ISSUE TITLE
Inverse/non-inverse percentage isn't correct for custom deadline

### ISSUE THREAD

**Issue by soguy** [BrianValente/yearprogress_mac#2]
Hi,
I got the updated version with this option. However, it seems to display wrong percentage for custom deadline with or without this option. See attached screenshot.

https://i.imgur.com/DnGs0zH.png

**Comment by BrianValente** [comment]
I'm sorry! Working on a fix ASAP

**Comment by BrianValente** [comment]
Can you try this build? https://brianvalente.com.ar/TimeProgress.zip

**Comment by BrianValente** [comment]
New build with a fix has been released to the App Store.
